### ISSUE TITLE
Active deployments with an end date will not be found in the /ingest/pax and /ingest/env endpoints

### ISSUE THREAD

**Issue by andriwild** [mitwelten/mitwelten-db-backend#67]
If deployments already have an end date that is in the future, the query will not find the deployment. This is because it assumes that the end date has not yet been set.

This can be remedied by changing the query to find deployments that have not yet reached their end date.

The changes affect the following endpoints:
- [ingest/pax](https://github.com/mitwelten/mitwelten-db-backend/blob/main/services/api/routers/ingest.py#L75C1-L79C14)
- [ingest/env](https://github.com/mitwelten/mitwelten-db-backend/blob/main/services/api/routers/ingest.py#L108C1-L112C14)

**Comment by cspindler** [comment]
Fixed in 0d29a703547839f1a6a28ac736148e57e3409255
